### ISSUE TITLE
你好，你的网站挺漂亮的啊，是拿什么现成的模板做的吗？还是vue 从头开发的？

### ISSUE THREAD

**Issue by dongrixinyu** [NoNormalCreeper/Kori-Bot#2]

**Comment by NoNormalCreeper** [comment]
首先，非常感谢您的认可 ヽ(°▽°)ノ
我的网站是用 WordPress 搭建的，而网站的这个主题是别的大佬写的现成的，名为 Sakurairo ，开源，项目的源地址在 https://github.com/mirai-mamori/Sakurairo 。
另：关于这个主题的版权信息也能在网站主页的最底下找到。
